import pygame

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 700
DISPLAY_CAPTION = "Blackjack"
CARD_WIDTH = 125
CARD_HEIGHT = 182
BUTTON_WIDTH = 86
BUTTON_HEIGHT = 86
BUTTON_HIT = pygame.K_RIGHT
BUTTON_STAND = pygame.K_LEFT
